steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/my-node-app:${BUILD_ID}', '.']

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/techlog-backend:${BUILD_ID}']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'techlog-backend'  # Replace with your desired service name
      - '--image'
      - 'gcr.io/${PROJECT_ID}/my-node-app:${BUILD_ID}'
      - '--region'
      - 'us-central1' # Choose your desired region
      - '--platform'
      - 'managed'  # Specifies the Cloud Run platform
      - '--allow-unauthenticated'
    # Example - Uncomment to allow unauthenticated access for testing:
    # env:
    #   - CLOUDSDK_CONTAINER_CLUSTER: your-cluster-name #  Needed in some cases.
    #   - CLOUDSDK_COMPUTE_ZONE: your-zone        # if a cluster is necessary
images:
  - 'gcr.io/${PROJECT_ID}/my-node-app:${BUILD_ID}'
